const C={
  red:0xff453a,blue:0x3287ff,yellow:0xffcf24,green:0x2ed66f,white:0xf8fbff,orange:0xff8d24,
  black:0x303841,pink:0xff58ad,silver:0xd4dde4,purple:0xa35cff,cyan:0x28d0ef,lime:0xa3ea2b,
  coral:0xff6f61,teal:0x28b8a7,gold:0xffb52e
};
const COLORS=Object.values(C);
const TYPES=['sedan','hatch','suv','luxury','taxi','van','delivery','sports','race','future','truck','flatbed','tractor','police','ambulance','fire'];
const THEMES=['park','shops','suburb','hospital','city','industrial','seaside','terminal','plaza'];
const TIMES=['day','morning','sunset','evening','night'];
const WEATHERS=['clear','sunny','cloudy','rain'];
function rng(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
const pick=(r,a)=>a[Math.floor(r()*a.length)];
function rotatePoint([x,z],q,mirror){if(mirror)x=-x;for(let i=0;i<q;i++)[x,z]=[-z,x];return[x,z]}
function baseShape(n,r){if(n===1)return[[0,0]];if(n===2)return r()<.5?[[-9,0],[9,0]]:[[0,-9],[0,9]];if(n===3){const v=Math.floor(r()*3);if(v===0)return[[-10,0],[0,0],[10,0]];if(v===1)return[[-8,-8],[8,-8],[8,8]];return[[-10,0],[0,0],[0,10]]}if(n===4){const v=Math.floor(r()*3);if(v===0)return[[-8,-8],[8,-8],[-8,8],[8,8]];if(v===1)return[[-12,0],[-4,0],[4,0],[12,0]];return[[-9,-7],[9,-7],[-9,7],[9,7]]}if(n===5){const v=Math.floor(r()*2);if(v===0)return[[0,0],[-10,0],[10,0],[0,-10],[0,10]];return[[-10,-7],[0,-7],[10,-7],[-10,7],[10,7]]}return[[-10,-7],[0,-7],[10,-7],[-10,7],[0,7],[10,7]]}
function connectIntersections(points){const edges=[];for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){const[a,b]=[points[i],points[j]];if(a[0]===b[0]){let blocked=false;for(let k=0;k<points.length;k++)if(k!==i&&k!==j&&points[k][0]===a[0]&&points[k][1]>Math.min(a[1],b[1])&&points[k][1]<Math.max(a[1],b[1])){blocked=true;break}if(!blocked)edges.push([i,j])}else if(a[1]===b[1]){let blocked=false;for(let k=0;k<points.length;k++)if(k!==i&&k!==j&&points[k][1]===a[1]&&points[k][0]>Math.min(a[0],b[0])&&points[k][0]<Math.max(a[0],b[0])){blocked=true;break}if(!blocked)edges.push([i,j])}}return edges}
function makeNetwork(levelNo){const r=rng(levelNo*7919+17),count=levelNo<=10?1:levelNo<=25?2:levelNo<=45?3:levelNo<=70?4:levelNo<=85?5:6;let pts=baseShape(count,r);const q=Math.floor(r()*4),mirror=r()>.5;pts=pts.map(p=>rotatePoint(p,q,mirror));const nodes=pts.map((p,i)=>({id:`I${i}`,x:p[0],z:p[1],intersection:true,boundary:false})),edges=connectIntersections(pts).map(([a,b])=>({a:`I${a}`,b:`I${b}`})),boundary=[],dirs=[['W',-1,0],['E',1,0],['N',0,-1],['S',0,1]],extent=28;pts.forEach((p,i)=>{for(const[d,dx,dz]of dirs){let has=false;for(let j=0;j<pts.length;j++)if(j!==i){const q=pts[j];if(dx&&q[1]===p[1]&&Math.sign(q[0]-p[0])===dx){let nearest=true;for(let k=0;k<pts.length;k++)if(k!==i&&k!==j&&pts[k][1]===p[1]&&Math.sign(pts[k][0]-p[0])===dx&&Math.abs(pts[k][0]-p[0])<Math.abs(q[0]-p[0]))nearest=false;if(nearest){has=true;break}}if(dz&&q[0]===p[0]&&Math.sign(q[1]-p[1])===dz){let nearest=true;for(let k=0;k<pts.length;k++)if(k!==i&&k!==j&&pts[k][0]===p[0]&&Math.sign(pts[k][1]-p[1])===dz&&Math.abs(pts[k][1]-p[1])<Math.abs(q[1]-p[1]))nearest=false;if(nearest){has=true;break}}}if(!has&&(count===1||r()>.24)){const id=`B${boundary.length}`,x=dx?(dx<0?-extent:extent):p[0],z=dz?(dz<0?-extent:extent):p[1];nodes.push({id,x,z,intersection:false,boundary:true,dir:d});boundary.push(id);edges.push({a:`I${i}`,b:id})}}});if(boundary.length<4){const p=pts[0];for(const[d,dx,dz]of dirs){if(boundary.length>=4)break;const x=dx?(dx<0?-extent:extent):p[0],z=dz?(dz<0?-extent:extent):p[1];if(nodes.some(n=>n.x===x&&n.z===z))continue;const id=`B${boundary.length}`;nodes.push({id,x,z,boundary:true,intersection:false,dir:d});boundary.push(id);edges.push({a:'I0',b:id})}}return{nodes,edges,boundary,intersectionCount:count}}
function adjacency(network){const a=new Map(network.nodes.map(n=>[n.id,[]]));for(const e of network.edges){a.get(e.a).push(e.b);a.get(e.b).push(e.a)}return a}
function pathIds(network,start,end){const adj=adjacency(network),q=[start],prev=new Map([[start,null]]);while(q.length){const cur=q.shift();if(cur===end)break;for(const nx of adj.get(cur)||[])if(!prev.has(nx)){prev.set(nx,cur);q.push(nx)}}if(!prev.has(end))return[start,end];const out=[];for(let c=end;c!=null;c=prev.get(c))out.push(c);return out.reverse()}
function lanePoints(network,ids,lane=1.85){const map=new Map(network.nodes.map(n=>[n.id,n])),p=ids.map(id=>[map.get(id).x,map.get(id).z]);return p.map((pt,i)=>{const normals=[];if(i>0){let dx=pt[0]-p[i-1][0],dz=pt[1]-p[i-1][1],l=Math.hypot(dx,dz)||1;dx/=l;dz/=l;normals.push([dz,-dx])}if(i<p.length-1){let dx=p[i+1][0]-pt[0],dz=p[i+1][1]-pt[1],l=Math.hypot(dx,dz)||1;dx/=l;dz/=l;normals.push([dz,-dx])}let nx=normals.reduce((s,n)=>s+n[0],0),nz=normals.reduce((s,n)=>s+n[1],0),nl=Math.hypot(nx,nz)||1;nx/=nl;nz/=nl;return[+(pt[0]+nx*lane).toFixed(2),+(pt[1]+nz*lane).toFixed(2)]})}
function routeLength(points){let d=0;for(let i=1;i<points.length;i++)d+=Math.hypot(points[i][0]-points[i-1][0],points[i][1]-points[i-1][1]);return d}
function makeVehicles(levelNo,network,r){const count=Math.min(18,4+Math.floor((levelNo-1)/6)),bs=[...network.boundary],srcUse=new Map(),vehicles=[];for(let i=0;i<count;i++){const src=bs[i%bs.length];let dst=bs[(i*2+1+Math.floor(r()*bs.length))%bs.length];if(dst===src)dst=bs[(bs.indexOf(src)+1)%bs.length];let ids=pathIds(network,src,dst),guard=0;while(ids.length<3&&guard++<8){dst=pick(r,bs.filter(b=>b!==src));ids=pathIds(network,src,dst)}const points=lanePoints(network,ids,1.75+(i%3)*.08),len=routeLength(points),queue=srcUse.get(src)||0;srcUse.set(src,queue+1);const start=Math.min(.34,.018+queue*(5/Math.max(34,len)));let type=TYPES[(levelNo+i*3+Math.floor(r()*TYPES.length))%TYPES.length];if(levelNo<6&&['police','ambulance','fire','tractor','flatbed'].includes(type))type=['sedan','hatch','suv','taxi','sports'][i%5];if(levelNo>=18&&i===0)type=['police','ambulance','fire'][levelNo%3];const speed=Math.max(3.7,5.05+(r()-.5)*1.2+(levelNo>70?.35:0)-(['truck','flatbed','tractor'].includes(type)?.75:0));vehicles.push({id:`L${levelNo}V${i}`,type,color:COLORS[(levelNo*5+i*2)%COLORS.length],route:{name:`${src}-${dst}`,points},start:+start.toFixed(3),speed:+speed.toFixed(2)})}return vehicles}
const trNames=['Başlangıç Akışı','Şehir Geçidi','Park Bağlantısı','Çarşı Düğümü','Hastane Hattı','Yoğun Saat','Sahil Akışı','Sanayi Bağlantısı','Terminal Düğümü','Meydan Trafiği','Çifte Kavşak','Dar Geçiş','Kritik Sıra','Acil Koridor','Karmaşık Ağ','Üçlü Düğüm','Gece Akışı','Yağmur Hattı','Yoğun Merkez','Usta Rotası'];
const enNames=['Opening Flow','City Crossing','Park Link','Market Junction','Hospital Route','Rush Hour','Coastal Flow','Industrial Link','Terminal Junction','Plaza Traffic','Double Junction','Narrow Passage','Critical Order','Emergency Corridor','Complex Network','Triple Junction','Night Flow','Rain Route','Dense Center','Master Route'];
function levelName(n,lang){const a=lang==='tr'?trNames:enNames;return`${a[(n-1)%a.length]} ${Math.ceil(n/20)}`}
export const levels=Array.from({length:100},(_,idx)=>{const n=idx+1,r=rng(n*104729+31),network=makeNetwork(n);let theme=THEMES[(n*3+Math.floor(r()*THEMES.length))%THEMES.length];const time=n%11===0||n%17===0?'night':n%7===0?'sunset':n%13===0?'evening':n%9===0?'morning':'day',weather=n%10===0||n%19===0?'rain':n%8===0?'cloudy':n%6===0?'sunny':'clear';if(n<=3)theme=['park','shops','suburb'][n-1];return{number:n,nameTR:levelName(n,'tr'),nameEN:levelName(n,'en'),theme,time,weather,network,intersectionCount:network.intersectionCount,decorSeed:n*4099+73,vehicles:makeVehicles(n,network,r)}});