import * as THREE from 'three';
import {levels} from './levels.js';
const canvas=document.querySelector('#game'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9ec9df);scene.fog=new THREE.Fog(0x9ec9df,35,58);
const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(20,25,22);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xe8f5ff,0x65704d,2.1));const sun=new THREE.DirectionalLight(0xfff0d0,3.1);sun.position.set(-12,24,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-24;sun.shadow.camera.right=24;sun.shadow.camera.top=24;sun.shadow.camera.bottom=-24;scene.add(sun);
const world=new THREE.Group(),vehicleLayer=new THREE.Group();scene.add(world,vehicleLayer);let levelIndex=0,vehicles=[],running=false,failed=false,unlocked=+(localStorage.tp3dUnlocked||1),audioOn=true;
const mat=(c,rough=.75)=>new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:.05});
function box(w,h,d,c,x,y,z,group=world){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.receiveShadow=true;m.castShadow=true;group.add(m);return m}
function buildWorld(theme){world.clear();box(48,.5,48,0x75a85e,0,-.4,0);box(48,.16,8,0x343b40,0,0,0);box(8,.17,48,0x343b40,0,.01,0);for(const z of [-2.8,2.8])for(let x=-22;x<23;x+=4)box(2,.025,.11,0xe9e3c8,x,.11,z);for(const x of [-2.8,2.8])for(let z=-22;z<23;z+=4)box(.11,.025,2,0xe9e3c8,x,.12,z);
 for(const [x,z] of [[-12,-12],[12,-12],[-12,12],[12,12]]){box(7,.45,7,0xb9b39f,x,-.05,z);const h=theme==='city'?6:3.5;box(5,h,5,theme==='hospital'?0xe7e8e4:0xd69c67,x,h/2,z);for(let i=-1;i<=1;i+=2)box(.7,.7,.05,0x82bdd1,x+i*1.2,h*.55,z+2.51);}
 for(const [x,z] of [[-8,-8],[8,-8],[-8,8],[8,8],[-18,-7],[18,7]]){box(.45,2.6,.45,0x6c4b32,x,1.3,z);const crown=new THREE.Mesh(new THREE.SphereGeometry(1.35,8,6),mat(0x3f8c4d));crown.position.set(x,3,z);crown.castShadow=true;world.add(crown)} }
function vehicleModel(v){const g=new THREE.Group(),dims={sedan:[2.6,.65,1.35],hatch:[2.35,.72,1.4],suv:[2.7,.9,1.48],taxi:[2.6,.68,1.38],van:[3,.95,1.5],ambulance:[3.25,1.05,1.55],police:[2.7,.7,1.4],fire:[3.5,1.15,1.55]}[v.type]||[2.6,.7,1.4],c=v.color;
 box(dims[0],dims[1],dims[2],c,0,.48,0,g);box(dims[0]*.52,.55,dims[2]*.88,v.type==='van'||v.type==='ambulance'||v.type==='fire'?c:0x7da1ad,-.15,1.02,0,g);
 for(const x of [-dims[0]*.32,dims[0]*.32])for(const z of [-dims[2]*.51,dims[2]*.51]){const wh=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,.2,12),mat(0x17191c));wh.rotation.x=Math.PI/2;wh.position.set(x,.32,z);g.add(wh)}
 if(['police','ambulance','fire'].includes(v.type)){box(.48,.12,.18,0x2979ff,0,1.38,-.18,g);box(.48,.12,.18,0xff304f,0,1.38,.18,g);g.userData.emergency=true} if(v.type==='taxi')box(.55,.18,.35,0xf6d54a,0,1.38,0,g);g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});return g}
function point(route,t){const n=route.length-1,p=Math.min(n-1,Math.floor(t*n)),f=t*n-p,a=route[p],b=route[p+1];return new THREE.Vector3(THREE.MathUtils.lerp(a[0],b[0],f),.12,THREE.MathUtils.lerp(a[1],b[1],f))}
function loadLevel(i){levelIndex=i;failed=false;vehicleLayer.clear();vehicles=[];buildWorld(levels[i].theme);for(const data of levels[i].vehicles){const mesh=vehicleModel(data),t=data.start||0,pos=point(data.route,t);mesh.position.copy(pos);const next=point(data.route,Math.min(.999,t+.01));mesh.rotation.y=-Math.atan2(next.z-pos.z,next.x-pos.x);mesh.userData.id=data.id;vehicleLayer.add(mesh);vehicles.push({...data,mesh,t,state:'waiting'})}document.querySelector('#levelLabel').textContent=i+1;updateRemaining();document.querySelector('#message').textContent=levels[i].name+' • Araca dokun';running=true}
function updateRemaining(){document.querySelector('#remaining').textContent=vehicles.filter(v=>v.state!=='done').length}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();canvas.addEventListener('pointerup',e=>{if(!running||failed)return;pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(vehicleLayer.children,true);if(!hits.length)return;let o=hits[0].object;while(o.parent!==vehicleLayer&&o.parent)o=o.parent;const v=vehicles.find(q=>q.mesh===o);if(v&&v.state==='waiting'){v.state='moving';document.querySelector('#message').textContent=v.mesh.userData.emergency?'Acil araç yolda!':'Araç hareket etti'}});
function collide(){const active=vehicles.filter(v=>v.state==='moving');for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const a=active[i],b=active[j];if(a.mesh.position.distanceTo(b.mesh.position)<1.45){a.state=b.state='crashed';failed=true;running=false;document.querySelector('#resultIcon').textContent='!';document.querySelector('#resultIcon').style.background='#ff5a5f';document.querySelector('#resultTitle').textContent='Çarpışma!';document.querySelector('#resultText').textContent='Sırayı değiştir ve tekrar dene.';document.querySelector('#nextBtn').style.display='none';document.querySelector('#result').classList.add('visible');return}}}
function win(){running=false;unlocked=Math.max(unlocked,Math.min(levels.length,levelIndex+2));localStorage.tp3dUnlocked=unlocked;document.querySelector('#resultIcon').textContent='✓';document.querySelector('#resultIcon').style.background='#54d98c';document.querySelector('#resultTitle').textContent='Yol Temiz!';document.querySelector('#resultText').textContent='Tüm araçları güvenle geçirdin.';document.querySelector('#nextBtn').style.display=levelIndex<levels.length-1?'block':'none';document.querySelector('#result').classList.add('visible')}
function tick(dt,time){if(running&&!failed){for(const v of vehicles){if(v.state!=='moving')continue;v.t+=dt*v.speed/42;if(v.t>=1){v.t=1;v.state='done';v.mesh.visible=false;updateRemaining();continue}const p=point(v.route,v.t),n=point(v.route,Math.min(.999,v.t+.008));v.mesh.position.copy(p);v.mesh.rotation.y=-Math.atan2(n.z-p.z,n.x-p.x);if(v.mesh.userData.emergency)v.mesh.children.slice(-2).forEach((x,k)=>x.visible=Math.floor(time/180+k)%2===0)}collide();if(!failed&&vehicles.length&&vehicles.every(v=>v.state==='done'))win()}}
let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min(.035,(now-last)/1000);last=now;tick(dt,now);renderer.render(scene,camera)}requestAnimationFrame(animate);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();buildWorld('park');
const menu=document.querySelector('#menu'),select=document.querySelector('#levelSelect'),result=document.querySelector('#result');document.querySelector('#playBtn').onclick=()=>{menu.classList.remove('visible');loadLevel(Math.min(unlocked-1,levels.length-1))};document.querySelector('#homeBtn').onclick=()=>{running=false;result.classList.remove('visible');select.classList.remove('visible');menu.classList.add('visible')};document.querySelector('#retryBtn').onclick=()=>{result.classList.remove('visible');loadLevel(levelIndex)};document.querySelector('#nextBtn').onclick=()=>{result.classList.remove('visible');loadLevel(Math.min(levelIndex+1,levels.length-1))};document.querySelector('#soundBtn').onclick=e=>{audioOn=!audioOn;e.currentTarget.textContent=audioOn?'🔊':'🔇'};
function grid(){const g=document.querySelector('#levelGrid');g.innerHTML='';levels.forEach((l,i)=>{const b=document.createElement('button');b.textContent=i+1;b.className=i>=unlocked?'locked':'';b.onclick=()=>{if(i>=unlocked)return;select.classList.remove('visible');menu.classList.remove('visible');loadLevel(i)};g.appendChild(b)})}document.querySelector('#levelsBtn').onclick=()=>{grid();menu.classList.remove('visible');select.classList.add('visible')};document.querySelector('#closeLevels').onclick=()=>{select.classList.remove('visible');menu.classList.add('visible')};
