import * as THREE from 'three';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
import {levels} from './levels.js';
import {createEnvironment} from './environment_v3.js';

const $=s=>document.querySelector(s),canvas=$('#game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.45));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,140),hemi=new THREE.HemisphereLight(0xf8fdff,0x43533b,1.6),sun=new THREE.DirectionalLight(0xffdfae,2.45);sun.position.set(-14,24,11);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-32;sun.shadow.camera.right=32;sun.shadow.camera.top=32;sun.shadow.camera.bottom=-32;scene.add(hemi,sun);
const world=new THREE.Group(),vehicleLayer=new THREE.Group(),effectsLayer=new THREE.Group(),weatherLayer=new THREE.Group();scene.add(world,vehicleLayer,effectsLayer,weatherLayer);
const environment=createEnvironment({scene,world,weatherLayer,camera,renderer,hemi,sun});
let levelIndex=0,vehicles=[],running=false,failed=false,loadToken=0,crashEffects=[],audioOn=true,unlocked=+(localStorage.tp3dUnlocked||1);

const mat=(c,r=.72,m=.03)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
function box(w,h,d,c,x,y,z,g,r=.72,m=.03){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,r,m));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;g.add(o);return o}
function wheel(g,x,z,r=.31){const t=new THREE.Mesh(new THREE.CylinderGeometry(r,r,.25,18),mat(0x111418,.86));t.rotation.z=Math.PI/2;t.position.set(x,.36,z);t.castShadow=true;g.add(t)}
function routeManeuver(route){const p=route.points;if(!p||p.length<2)return'straight';const a=p[0],b=p[1],c=p[p.length-2],d=p[p.length-1];let ix=b[0]-a[0],iz=b[1]-a[1],ox=d[0]-c[0],oz=d[1]-c[1];const il=Math.hypot(ix,iz)||1,ol=Math.hypot(ox,oz)||1;ix/=il;iz/=il;ox/=ol;oz/=ol;if(ix*ox+iz*oz>.72)return'straight';return iz*ox-ix*oz>0?'left':'right'}
const maneuverLabel=k=>k==='left'?'SOL':k==='right'?'SAĞ':'DÜZ';
const arrowTextures={};
function arrowTexture(kind){const c=document.createElement('canvas');c.width=320;c.height=360;const x=c.getContext('2d');x.fillStyle='rgba(17,24,39,.92)';x.beginPath();x.roundRect(28,18,264,320,54);x.fill();x.strokeStyle='rgba(255,255,255,.25)';x.lineWidth=6;x.stroke();x.strokeStyle=x.fillStyle='#ffdf37';x.lineWidth=34;x.lineCap='round';x.lineJoin='round';x.beginPath();if(kind==='left'){x.moveTo(180,235);x.lineTo(180,166);x.quadraticCurveTo(180,112,126,112);x.lineTo(86,112);x.stroke();x.beginPath();x.moveTo(82,112);x.lineTo(126,72);x.lineTo(126,152);x.closePath();x.fill()}else if(kind==='right'){x.moveTo(140,235);x.lineTo(140,166);x.quadraticCurveTo(140,112,194,112);x.lineTo(234,112);x.stroke();x.beginPath();x.moveTo(238,112);x.lineTo(194,72);x.lineTo(194,152);x.closePath();x.fill()}else{x.moveTo(160,238);x.lineTo(160,108);x.stroke();x.beginPath();x.moveTo(160,62);x.lineTo(112,120);x.lineTo(208,120);x.closePath();x.fill()}x.fillStyle='#fff';x.font='800 44px system-ui';x.textAlign='center';x.fillText(maneuverLabel(kind),160,308);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function addArrow(g,type,kind){if(!arrowTextures[kind])arrowTextures[kind]=arrowTexture(kind);const h=type==='fire'?2.55:['truck','flatbed','delivery','ambulance','van','tractor'].includes(type)?2.3:['suv','luxury'].includes(type)?2.05:1.9;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:arrowTextures[kind],transparent:true,depthTest:false,depthWrite:false}));s.position.set(0,h+.55,0);s.scale.set(1.55,1.75,1);s.renderOrder=30;g.add(s);g.userData.arrow=s}
function fallback(v,kind){const g=new THREE.Group(),big=['van','delivery','flatbed','ambulance','fire','truck','tractor'].includes(v.type),L=v.type==='fire'?4.2:['truck','flatbed','delivery'].includes(v.type)?3.7:big?3.5:['suv','luxury'].includes(v.type)?3.15:2.95,W=big?1.58:1.45,H=big?1.02:['suv','luxury'].includes(v.type)?.86:.7,c=v.color||0xff4b45;box(W,H,L,c,0,.58,0,g,.3,.18);box(W*.83,big?.64:.52,big?L*.46:L*.48,big?c:0x376d83,0,big?1.26:1.17,-.2,g,.2,.12);for(const x of[-W*.51,W*.51])for(const z of[-L*.31,L*.31])wheel(g,x,z,big?.34:.3);if(['police','ambulance','fire'].includes(v.type)){const a=box(.42,.12,.22,0x2d78ff,-.25,1.58,0,g),b=box(.42,.12,.22,0xff3f4e,.25,1.58,0,g);a.material=new THREE.MeshStandardMaterial({color:0x327cff,emissive:0x135dff,emissiveIntensity:1.7});b.material=new THREE.MeshStandardMaterial({color:0xff3f4e,emissive:0xff1026,emissiveIntensity:1.7});g.userData.flash=[a,b]}g.userData.emergency=['police','ambulance','fire'].includes(v.type);addArrow(g,v.type,kind);return g}

const loader=new GLTFLoader(),BASE='https://cdn.jsdelivr.net/gh/kidscancode/3d_car_sphere@cabc5c0019e68913012fc41d7b2ded6dcef3be31/assets/kenney_car_kit/';
const carFiles={sedan:'sedan.glb',hatch:'hatchbackSports.glb',suv:'suv.glb',luxury:'suvLuxury.glb',taxi:'taxi.glb',van:'van.glb',delivery:'delivery.glb',flatbed:'truckFlat.glb',truck:'truck.glb',tractor:'tractor.glb',ambulance:'ambulance.glb',police:'police.glb',fire:'firetruck.glb',sports:'sedanSports.glb',race:'race.glb',future:'raceFuture.glb'},cache=new Map();
function getAsset(type){const f=carFiles[type]||carFiles.sedan;if(cache.has(f))return cache.get(f);const p=new Promise((res,rej)=>loader.load(BASE+f,g=>res(g.scene),undefined,rej));cache.set(f,p);return p}
function normalize(src,v,kind){const outer=new THREE.Group(),model=src.clone(true);outer.add(model);model.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;if(o.material)o.material=o.material.clone()}});let b=new THREE.Box3().setFromObject(model),s=b.getSize(new THREE.Vector3()),target=v.type==='fire'?4.2:['truck','flatbed','delivery'].includes(v.type)?3.7:['ambulance','van','tractor'].includes(v.type)?3.5:['suv','luxury'].includes(v.type)?3.15:2.95;model.scale.setScalar(target/(Math.max(s.x,s.z)||1));model.rotation.y=Math.PI;b=new THREE.Box3().setFromObject(model);const cc=b.getCenter(new THREE.Vector3());model.position.x-=cc.x;model.position.z-=cc.z;model.position.y-=b.min.y-.13;if(['police','ambulance','fire'].includes(v.type)){const a=box(.36,.09,.18,0x2d78ff,-.22,1.45,0,outer),bb=box(.36,.09,.18,0xff3f4e,.22,1.45,0,outer);a.material=new THREE.MeshStandardMaterial({color:0x327cff,emissive:0x135dff,emissiveIntensity:2});bb.material=new THREE.MeshStandardMaterial({color:0xff3f4e,emissive:0xff1026,emissiveIntensity:2});outer.userData.flash=[a,bb];outer.userData.emergency=true}addArrow(outer,v.type,kind);return outer}
async function upgrade(v,token){try{const src=await getAsset(v.type);if(token!==loadToken||!v.mesh||v.state==='done')return;const n=normalize(src,v,v.maneuver);n.position.copy(v.mesh.position);n.rotation.copy(v.mesh.rotation);n.visible=v.mesh.visible;if(n.userData.arrow)n.userData.arrow.visible=v.state==='waiting';vehicleLayer.remove(v.mesh);vehicleLayer.add(n);v.mesh=n}catch(e){console.warn('model fallback',v.type)}}
function curveFor(route){const c=new THREE.CatmullRomCurve3(route.points.map(p=>new THREE.Vector3(p[0],.13,p[1])),false,'centripetal',.28);c.arcLengthDivisions=320;return c}
function place(v){const u=THREE.MathUtils.clamp(v.distance/v.length,0,.99999),p=v.curve.getPointAt(u),t=v.curve.getTangentAt(u);v.mesh.position.copy(p);v.mesh.rotation.y=Math.atan2(t.x,t.z)}
function dims(t){if(t==='fire')return[4.15,1.6];if(['truck','flatbed','delivery'].includes(t))return[3.7,1.58];if(['ambulance','van','tractor'].includes(t))return[3.5,1.56];if(['suv','luxury'].includes(t))return[3.15,1.5];return[2.95,1.43]}
function obb(v){const[L,W]=dims(v.type),a=v.mesh.rotation.y,s=Math.sin(a),c=Math.cos(a);return{x:v.mesh.position.x,z:v.mesh.position.z,fx:s,fz:c,rx:c,rz:-s,hl:L*.46+.04,hw:W*.45+.03}}
const radius=(b,ax,az)=>b.hl*Math.abs(ax*b.fx+az*b.fz)+b.hw*Math.abs(ax*b.rx+az*b.rz);
function overlap(a,b){const A=obb(a),B=obb(b),dx=B.x-A.x,dz=B.z-A.z,axes=[[A.fx,A.fz],[A.rx,A.rz],[B.fx,B.fz],[B.rx,B.rz]];for(const[ax,az]of axes)if(Math.abs(dx*ax+dz*az)>=radius(A,ax,az)+radius(B,ax,az))return false;return true}
function collision(){for(let i=0;i<vehicles.length;i++)for(let j=i+1;j<vehicles.length;j++){const a=vehicles[i],b=vehicles[j];if(a.state==='done'||b.state==='done'||(a.state!=='moving'&&b.state!=='moving'))continue;if(overlap(a,b))return[a,b]}return null}

let audioCtx=null,masterGain=null,ambient=null;
function ensureAudio(){if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();masterGain.gain.value=audioOn?.52:0;masterGain.connect(audioCtx.destination)}if(audioCtx.state==='suspended')audioCtx.resume();if(!ambient&&audioOn)startAmbient()}
function startAmbient(){if(!audioCtx||ambient)return;const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.18;const src=audioCtx.createBufferSource(),filter=audioCtx.createBiquadFilter(),gain=audioCtx.createGain();src.buffer=buffer;src.loop=true;filter.type='lowpass';filter.frequency.value=260;gain.gain.value=.032;src.connect(filter);filter.connect(gain);gain.connect(masterGain);src.start();ambient={src,gain}}
function beep(freq,dur=.12,vol=.08,type='sine',when=0){if(!audioOn)return;ensureAudio();const t=audioCtx.currentTime+when,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(masterGain);o.start(t);o.stop(t+dur+.03)}
function startSound(v){if(!audioOn||v.sound)return;ensureAudio();const heavy=['truck','flatbed','delivery','van','fire','ambulance','tractor'].includes(v.type),sport=['sports','race','future'].includes(v.type),o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='sawtooth';o.frequency.value=heavy?54:sport?116:76;f.type='lowpass';f.frequency.value=heavy?380:680;g.gain.value=heavy?.035:.024;o.connect(f);f.connect(g);g.connect(masterGain);o.start();v.sound={engine:o,engineGain:g};if(['police','ambulance','fire'].includes(v.type)){const sir=audioCtx.createOscillator(),sg=audioCtx.createGain(),lfo=audioCtx.createOscillator(),lg=audioCtx.createGain();sir.frequency.value=v.type==='police'?720:v.type==='ambulance'?640:520;sg.gain.value=v.type==='fire'?.06:.05;lfo.frequency.value=v.type==='police'?1.45:v.type==='ambulance'?1.05:.82;lg.gain.value=v.type==='fire'?150:210;lfo.connect(lg);lg.connect(sir.frequency);sir.connect(sg);sg.connect(masterGain);sir.start();lfo.start();v.sound.siren=sir;v.sound.sirenGain=sg;v.sound.lfo=lfo}}
function stopSound(v){if(!v.sound||!audioCtx){v.sound=null;return}const t=audioCtx.currentTime;for(const k of['engineGain','sirenGain'])if(v.sound[k]){v.sound[k].gain.setTargetAtTime(.0001,t,.03)}for(const k of['engine','siren','lfo'])if(v.sound[k])try{v.sound[k].stop(t+.15)}catch{}v.sound=null}
const stopAll=()=>vehicles.forEach(stopSound);
function crashSound(){beep(92,.3,.2,'sawtooth');beep(55,.38,.16,'square',.03)}
function winSound(){beep(523,.11,.08);beep(659,.11,.08,'sine',.12);beep(784,.18,.09,'sine',.24)}
function crashFx(a,b){const c=new THREE.Vector3().addVectors(a.mesh.position,b.mesh.position).multiplyScalar(.5);c.y=.8;const root=new THREE.Group();root.position.copy(c);effectsLayer.add(root);const flash=new THREE.PointLight(0xffc34a,5,9,2);root.add(flash);const parts=[];for(let i=0;i<18;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,.24),new THREE.MeshBasicMaterial({color:i%2?0xffa428:0xffffff,transparent:true}));root.add(m);parts.push({m,v:new THREE.Vector3((Math.random()-.5)*6,2+Math.random()*4,(Math.random()-.5)*6)})}crashEffects.push({root,flash,parts,age:0})}
function updateFx(dt){for(let i=crashEffects.length-1;i>=0;i--){const e=crashEffects[i];e.age+=dt;e.flash.intensity=Math.max(0,5*(1-e.age*3));for(const p of e.parts){p.v.y-=7*dt;p.m.position.addScaledVector(p.v,dt);p.m.material.opacity=Math.max(0,1-e.age)}if(e.age>1.1){effectsLayer.remove(e.root);crashEffects.splice(i,1)}}}

function loadLevel(i){stopAll();const token=++loadToken;levelIndex=i;failed=false;running=false;vehicleLayer.clear();vehicles=[];environment.build(levels[i],i);$('#levelLabel').textContent=i+1;$('#message').textContent=levels[i].name+' • Okları okuyup doğru sırayı seç';for(const d of levels[i].vehicles){const maneuver=routeManeuver(d.route),mesh=fallback(d,maneuver),curve=curveFor(d.route),length=curve.getLength(),v={...d,maneuver,mesh,curve,length,distance:(d.start||0)*length,state:'waiting',sound:null,prev:null};place(v);vehicleLayer.add(mesh);vehicles.push(v);upgrade(v,token)}updateRemaining();running=true}
function updateRemaining(){$('#remaining').textContent=vehicles.filter(v=>v.state!=='done').length}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
canvas.addEventListener('pointerup',e=>{if(!running||failed)return;ensureAudio();const r=canvas.getBoundingClientRect();pointer.set(((e.clientX-r.left)/r.width)*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pointer,camera);const h=ray.intersectObjects(vehicleLayer.children,true);if(!h.length)return;let o=h[0].object;while(o.parent!==vehicleLayer&&o.parent)o=o.parent;const v=vehicles.find(q=>q.mesh===o);if(v?.state==='waiting'){v.state='moving';if(v.mesh.userData.arrow)v.mesh.userData.arrow.visible=false;startSound(v);$('#message').textContent=v.mesh.userData.emergency?'Acil araç rotasında ilerliyor':`${maneuverLabel(v.maneuver)} rotası başladı`}})
function fail(pair){const[a,b]=pair;for(const v of vehicles)if(v.prev&&v.state==='moving'){v.mesh.position.copy(v.prev.p);v.mesh.rotation.y=v.prev.r}crashFx(a,b);failed=true;running=false;stopAll();crashSound();$('#resultIcon').textContent='!';$('#resultIcon').style.background='#ff5a5f';$('#resultTitle').textContent='Çarpışma!';$('#resultText').textContent='Araçların rotaları çakıştı. Çıkış sırasını değiştir.';$('#nextBtn').style.display='none';$('#result').classList.add('visible')}
function win(){running=false;stopAll();winSound();unlocked=Math.max(unlocked,Math.min(levels.length,levelIndex+2));localStorage.tp3dUnlocked=unlocked;$('#resultIcon').textContent='✓';$('#resultIcon').style.background='#54d98c';$('#resultTitle').textContent='Yol Temiz!';$('#resultText').textContent='Tüm araçları güvenle geçirdin.';$('#nextBtn').style.display=levelIndex<levels.length-1?'block':'none';$('#result').classList.add('visible')}
function tick(dt,now){if(!running||failed)return;for(const v of vehicles){if(v.mesh.userData.flash){const on=Math.floor(now/220)%2===0;v.mesh.userData.flash[0].visible=on;v.mesh.userData.flash[1].visible=!on}v.prev=null;if(v.state!=='moving')continue;v.prev={p:v.mesh.position.clone(),r:v.mesh.rotation.y};v.distance+=v.speed*dt;if(v.distance>=v.length){v.distance=v.length;v.state='done';stopSound(v);v.mesh.visible=false;updateRemaining();continue}place(v)}const h=collision();if(h)return fail(h);if(vehicles.length&&vehicles.every(v=>v.state==='done'))win()}
let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min(.035,(now-last)/1000);tick(dt,now);environment.update(dt,now);updateFx(dt);last=now;renderer.render(scene,camera)}requestAnimationFrame(animate);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();environment.build(levels[0],0);
const menu=$('#menu'),select=$('#levelSelect'),result=$('#result');$('#playBtn').onclick=()=>{ensureAudio();menu.classList.remove('visible');loadLevel(Math.min(unlocked-1,levels.length-1))};$('#homeBtn').onclick=()=>{stopAll();++loadToken;running=false;result.classList.remove('visible');select.classList.remove('visible');menu.classList.add('visible')};$('#retryBtn').onclick=()=>{result.classList.remove('visible');loadLevel(levelIndex)};$('#nextBtn').onclick=()=>{result.classList.remove('visible');loadLevel(Math.min(levelIndex+1,levels.length-1))};$('#soundBtn').onclick=e=>{audioOn=!audioOn;e.currentTarget.textContent=audioOn?'🔊':'🔇';if(masterGain)masterGain.gain.setTargetAtTime(audioOn?.52:0,audioCtx.currentTime,.03)};function grid(){const g=$('#levelGrid');g.innerHTML='';levels.forEach((l,i)=>{const b=document.createElement('button');b.textContent=i+1;b.className=i>=unlocked?'locked':'';b.onclick=()=>{if(i>=unlocked)return;ensureAudio();select.classList.remove('visible');menu.classList.remove('visible');loadLevel(i)};g.appendChild(b)})}$('#levelsBtn').onclick=()=>{grid();menu.classList.remove('visible');select.classList.add('visible')};$('#closeLevels').onclick=()=>{select.classList.remove('visible');menu.classList.add('visible')};Object.keys(carFiles).forEach(t=>getAsset(t).catch(()=>{}));
